// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.1
// source: phoneclient.proto

// user 包

package tdclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User 服务的各个接口的请求/响应结构
type ClientRegRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone     string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Phonecode string `protobuf:"bytes,2,opt,name=phonecode,proto3" json:"phonecode,omitempty"`
}

func (x *ClientRegRequest) Reset() {
	*x = ClientRegRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phoneclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRegRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegRequest) ProtoMessage() {}

func (x *ClientRegRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phoneclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegRequest.ProtoReflect.Descriptor instead.
func (*ClientRegRequest) Descriptor() ([]byte, []int) {
	return file_phoneclient_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRegRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ClientRegRequest) GetPhonecode() string {
	if x != nil {
		return x.Phonecode
	}
	return ""
}

type ClientRegResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err int32  `protobuf:"varint,1,opt,name=err,proto3" json:"err,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ClientRegResponse) Reset() {
	*x = ClientRegResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phoneclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRegResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegResponse) ProtoMessage() {}

func (x *ClientRegResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phoneclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegResponse.ProtoReflect.Descriptor instead.
func (*ClientRegResponse) Descriptor() ([]byte, []int) {
	return file_phoneclient_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRegResponse) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *ClientRegResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_phoneclient_proto protoreflect.FileDescriptor

var file_phoneclient_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x46, 0x0a,
	0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x37, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x4f,
	0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x2e, 0x74, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x74, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0b, 0x5a, 0x09, 0x2f, 0x74, 0x64, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phoneclient_proto_rawDescOnce sync.Once
	file_phoneclient_proto_rawDescData = file_phoneclient_proto_rawDesc
)

func file_phoneclient_proto_rawDescGZIP() []byte {
	file_phoneclient_proto_rawDescOnce.Do(func() {
		file_phoneclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_phoneclient_proto_rawDescData)
	})
	return file_phoneclient_proto_rawDescData
}

var file_phoneclient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_phoneclient_proto_goTypes = []interface{}{
	(*ClientRegRequest)(nil),  // 0: tdclient.ClientRegRequest
	(*ClientRegResponse)(nil), // 1: tdclient.ClientRegResponse
}
var file_phoneclient_proto_depIdxs = []int32{
	0, // 0: tdclient.Client.RegPhone:input_type -> tdclient.ClientRegRequest
	1, // 1: tdclient.Client.RegPhone:output_type -> tdclient.ClientRegResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phoneclient_proto_init() }
func file_phoneclient_proto_init() {
	if File_phoneclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phoneclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRegRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phoneclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRegResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phoneclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phoneclient_proto_goTypes,
		DependencyIndexes: file_phoneclient_proto_depIdxs,
		MessageInfos:      file_phoneclient_proto_msgTypes,
	}.Build()
	File_phoneclient_proto = out.File
	file_phoneclient_proto_rawDesc = nil
	file_phoneclient_proto_goTypes = nil
	file_phoneclient_proto_depIdxs = nil
}
