package model

type Agent struct {
	Name  string `json:"name"`
	Agent int    `json:"agent"`
}

// User has a name, department and created date. Name and created are required, department is optional.
// Id is auto-generated by database after the user is persisted.
// json is for couchdb
type Me struct {
	Name  string `json:"name"`
	Agent int    `json:"agent"`
}

// ALTER TABLE `td`.`groups`
// ADD COLUMN `verified` INT NULL DEFAULT 0 COMMENT '1 需要验证' AFTER `linkurl`;

type Groups struct {
	Name     string `json:"name"`
	Linkurl  string `json:"linkurl"`
	Agent    int    `json:"agent"`
	Verified int    `json:"Verified"`
}

// User has a name, department and created date. Name and created are required, department is optional.
// Id is auto-generated by database after the user is persisted.
// json is for couchdb
type Groupinfos struct {
	Phone     string `json:"phone"`
	Groupname string `json:"groupname"`
	Agent     int    `json:"agent"`
}
