package model

// User has a name, department and created date. Name and created are required, department is optional.
// Id is auto-generated by database after the user is persisted.
// json is for couchdb
type Groups struct {
	Name    string `json:"name"`
	Linkurl string `json:"linkurl"`
}

// User has a name, department and created date. Name and created are required, department is optional.
// Id is auto-generated by database after the user is persisted.
// json is for couchdb
type Groupinfos struct {
	Phone     string `json:"phone"`
	Groupname string `json:"groupname"`
}
