// Package model represents domain model. Every domain model type should have it's own file.
// It shouldn't depends on any other package in the application.
// It should only has domain model type and limited domain logic, in this example, validation logic. Because all other
// package depends on this package, the import of this package should be as small as possible.

package model

// User has a name, department and created date. Name and created are required, department is optional.
// Id is auto-generated by database after the user is persisted.
// json is for couchdb

type Client struct {
	Id          int32  `json:"uid"`
	Name        string `json:"firstName"`
	Username    string `json:"username"`
	PhoneNumber string `json:"phoneNumber"`
}
