//对应数据库表模型
package model

import (
	"time"
)

// User has a name, department and created date. Name and created are required, department is optional.
// Id is auto-generated by database after the user is persisted.
// json is for couchdb
type Phone struct {
	Id          int       `json:"uid"`
	Phone       string    `json:"phone"`
	NickName    string    `json:"nickName"`
	Country     string    `json:"country"`
	Created     time.Time `json:"created"`
	ActivedTime time.Time `json:"Activedtime"` //上次活动时间
	File        string    `json:"file"`
	DB          string    `json:"db"` //db文件
}

//当前活动的手机
type PhoneSession struct {
	Id       int    `json:"uid"`
	Phone    string `json:"phone"`
	NickName string `json:"nickName"`
}

type Groups struct {
	Id          int       `json:"uid"`
	Name        string    `json:"name"`
	Url         string    `json:"nickName"`
	Country     string    `json:"country"`
	Created     time.Time `json:"created"`
	ActivedTime time.Time `json:"Activedtime"` //上次活动时间
}

// // Validate validates a newly created user, which has not persisted to database yet, so Id is empty
// func (u User) Validate() error {
// 	return validation.ValidateStruct(&u,
// 		validation.Field(&u.Name, validation.Required),
// 		validation.Field(&u.Created, validation.Required))
// }

// //ValidatePersisted validate a user that has been persisted to database, basically Id is not empty
// func (u User) ValidatePersisted() error {
// 	return validation.ValidateStruct(&u,
// 		validation.Field(&u.Id, validation.Required),
// 		validation.Field(&u.Name, validation.Required),
// 		validation.Field(&u.Created, validation.Required))
// }
